#+TITLE: 健身
#+HTML_LINK_UP: ../index.html

* 個人素質檢測
** 身體質量指數 BMI
計算身體質量指數 ( Body Mass Index 簡稱 BMI )

- 身體質量指數不適用於未滿18歲、運動員、正在做重量訓練、 懷孕或哺乳中女性、身體虛弱或久坐不動的老人
- 人體健康最理想的數值被世界衛生組織認定為：22
- 身體質量指數 ＝ 體重 ( 公斤 ) 除以身高 ( 公尺 ) 的平方 ( BMI ＝ Kg/m2 )
** 基礎代謝率 BMR
** 靜態能量消耗 
靜態能量消耗值(Resting Energy Expenditure，簡稱REE)：是指一般人所需的最小熱能需求量。其計算公式如下：(體重單位為公斤，身高單位為公分)
- 女性 REE = (10 × 體重) +(6.25 × 身高) - (5 × 年齡) - 161
- 男性 REE = (10 × 體重) +(6.25 × 身高) - (5 × 年齡) + 5
** 燃脂運動最佳心率計算
1.運動過程中心率要達到中低強度運動心率；
1. 運動要持續20分鐘以上； 
2. 必須是大肌肉群的運動，如慢跑、游泳、健身操等。

* 三餐內容
- 早 : 400ml 無糖豆漿 + 一根香蕉 + 一個水煮蛋
- 午 : 一肉一蛋一菜
- 宛 : subway 不加醬
- 
* 觀念 
1‧吃食物，不是食品
 香腸、蛋糕、醬菜、蜜餞、火腿培根等，都是「食品」並非食物，要減肥，一定要吃未經加工的「食物」，如蔬菜、水果、蛋、肉類，越天然越好。
2‧飲食烹調方式
油炸、油煎、油炒、勾芡和醃製，是減肥時最好少碰的烹調方式，建議改蒸、煮、水炒、烤代替，所以我都簡單的用水煮，也比較快。
3‧戒零食
身體所需要的醣類是「多糖」而不是單糖，甜食大多都是單糖，如蔗糖、果糖，吃多了只會讓脂肪快速長大，我都吃水果代替。
4‧細嚼慢嚥慢慢吃
吃太快很容易不知不覺吃過多，慢慢吃，在咀嚼的過程中給大腦吃飽的訊息，細嚼慢嚥會使食物充分與唾液中的酵素混合，讓食物完全分解，也減少胃部的負擔，所以我吃飯都很慢。
5‧餐餐8分飽
吃過飽會把胃撐大，反而越吃越多，我都吃7~8分飽，所以現在胃口比以往小。
6‧改變進食順序
吃飯時先吃蔬菜，然後喝湯或水，增加飽足感，然後在開始吃飯、魚、肉、蛋等其他食物......，我個人順序是溫水、蔬菜、蛋、魚、肉、飯。
7‧戒掉宵夜惡習
晚上8點以後盡量不要再吃東西，因為8點以後吃飯，不但沒辦法讓腸胃休息，反而讓脂肪堆積，喜歡吃宵夜的更應該戒掉10點後吃東西的習慣。我6點吃完，晚餐後就不會在進食只喝水。
8‧搭配有氧運動
要減掉脂肪，光靠飲食控制有限，最好加入一些有氧運動及肌肉訓練，即使走路也能達到效果。

* 參考資料
- [[https://pragprog.com/book/jkthp/the-healthy-programmer][Healthy Programmer]], Joe Kutner, 2013
