#+TITLE: 垃圾話
#+OPTIONS: H2
#+HTML_LINK_HOME: ../index.html
#+HTML_LINK_UP: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="/blog/css/readtheorg.css" />

* 會議室裡遺失的東西
K: 「有同學在會議室裡遺失重要的東西嗎？」

A: 「青春。」

source: bobchao's facebook.
* 笑即是殘酷 
Mikimoto: 根據幸福守恆定律，有生物笑的時候，一定有生物倒楣，所以笑的人都很殘酷。
* 生存、質疑與事故
Mikimoto: 所有的事情都會分成三個階段：「生存、質疑與世故」，例如以吃飯來說，一剛開始，你會告訴自己要吃飯，之後你會問為什麼要吃飯，最後你會問自己還有什麼東西可以吃
* 四句話總結人的一生
喜歡上一個人

喜歡上一個人

喜歡上一個人

喜歡上一個人

source: https://t.co/JQBvV4Hb2R
* JavaScript 帶給人類的啟示
javascript 告訴我們一件事，本身優不優秀不重要，重點是生對地方....
* 為什麼幸福的家庭都一個樣? 不幸的家庭都不一樣？
幸福的家庭都一個樣，不幸的家庭則家家有本難念的經。

為什麼呢？

讓工程師來告訴你：幸福的判斷式是 &&，不幸的判斷式是 ||；同時滿足所有條件才能變成幸福家庭，任一條件不滿足都會變成不幸家庭。
* 空虛與複雜
小孩的精神很豐富，所以他們的玩具很簡單。

大人的玩具很複雜，所以他們的精神很空虛。
* 矛盾何來
矛盾何來，皆因製杖販劍
* 一無所有
不要再說你一無所有了，你不是有病嗎？
* 跟工科大學生談生涯規劃
友人問曰: 「要跟大學生講職場、生涯規劃，大家覺得應該講些什麼」？

有鄉民答曰: 「工程師怎麼娶到好老婆的」

再有鄉民答曰: 「30歲前討到好老婆不能不知道的30件事」

友人妻奇道: 「所以取老婆比較重要？」

另有鄉民回道 :「娶對，就是人生。 娶錯，就是殘生。」
* 公司來了新人，姓蔡
男的叫蔡比巴, 女的叫菜菜子
* Duck Typing
什麼叫做 duck typing, 只要這個女生化妝起來像正妹，修圖後像正妹，整形後像正妹，那她就是個正妹。
* 熱情與初戀
Pingooo: 熱情就像初戀，一旦失去了，就很難追回來
* 阿宅都很忙
Jserv: 要說多少次，阿宅們都很忙碌的呀，不會因為居家就會很有空
* 要改的地方太多
Clkao: 要改的地方太多了，就改天
* 註定失敗
「從什麼時候開始決定你的人生注定失敗？」

『呃，當精子的時候？』
* 那就改天
改天就是永遠沒有那一天
* 大學專題該做什麼
Cindy: 專題就做 Lambda 仿生獸吧!

大二生: 這東西能做什麼用。

Cindy: 學生專題就是要做沒用但有梗的東西，要做有用能賺錢的東西，你之後的機會很多。
