#+TITLE: 別人的句子
#+HTML_LINK_UP: ./index.html

* 人生

#+BEGIN_QUOTE
快樂大抵是相同的，因為我們刻意地追求，但悲傷，每個人的都不同，也使每個人不同。 ~ 馬欣，當代寂寞考
#+END_QUOTE

#+BEGIN_QUOTE
生命不過是行走的影子，可憐的演員在舞台上昂首又垂頭，事過境遷，消逝無痕，這是一則白癡講的故事，滿是激昂語氣卻毫無意義。 ~ 莎士比亞, 馬克白
#+END_QUOTE

#+BEGIN_QUOTE
站在門下，何安下思緒萬千。想自己十六歲求道，至今經歷太多的人和事，學過太多的功法，卻依然沒找到活著的核心。 ~ 道士下山
#+END_QUOTE

#+BEGIN_QUOTE
一幅對聯「告別山中寂寞，迎來世間煩惱」，橫批為「自救救人」 ~ 道士下山
#+END_QUOTE

#+BEGIN_QUOTE
崇高必墮落，歡愛必離別。緣聚緣散，不過如此，還是看開了吧。 ~ 道士下山
#+END_QUOTE

#+BEGIN_QUOTE
世界滿是假象，我行的也是邪道。 畢竟你贏了。 ~ 道士下山
#+END_QUOTE

#+BEGIN_QUOTE
而你這個別人眼中的魯蛇，因為落單，才有可能撿起別人的錯過的珍貴價值。 ~ 馬欣，當代寂寞考
#+END_QUOTE

#+BEGIN_QUOTE 
我們棲息於光纖上，日日啄食網路的細沙，一如夏季的知了。 ~ 馬欣，當代寂寞考
#+END_QUOTE

#+BEGIN_QUOTE
需要掌聲的禮貌男士則大批移居到網路世界中，那裡的人們掌聲如雷，四處響起，「有些人忙到帽子幾乎沒時間再戴上了。」小王子說。 ~ 馬欣，當代寂寞考
#+END_QUOTE

* 人類
#+BEGIN_QUOTE
人們只看得到表象，但真正的事情發生在心裡，沒人會去看心裡的東西，也許是因為他們不在乎。我真的覺得這是人類有臉孔的原因，就是為了隱藏靈魂。 ~ 據說，我曾經是人類
#+END_QUOTE

* 成長

#+BEGIN_QUOTE
有人問我長大要做什麼，我寫下「快樂」，他們說我沒聽懂問題，我說他們不懂人生。 ~ 約翰。藍儂
#+END_QUOTE

#+BEGIN_QUOTE
大人是什麼？ 是我們說謊，他們才會相信的一群人嗎? ~ 四百擊
#+END_QUOTE

#+BEGIN_QUOTE
成人不是小孩死去，而是小孩倖存。 ~ 勒瑰恩
#+END_QUOTE

#+BEGIN_QUOTE
每個人都將不合時宜的老去，更將不合時宜的必須飛翔。 ~ 馬欣，當代寂寞考
#+END_QUOTE

#+BEGIN_QUOTE
有一天，他們把所有的希望都列出了價目表，但我仍不懂絕望。 ~ 馬欣，當代寂寞考
#+END_QUOTE

#+BEGIN_QUOTE
人的生日，並不單單是媽媽生你的那一天，還有很多，能令你心境改觀的，便是你的生日。 ~ 道士下山
#+END_QUOTE

* 他人眼中的你

#+BEGIN_QUOTE
你的眼睛塞滿了眼睛。透過你的眼窩，許多人盯著我看。他們的好奇心像是潑到我皮膚上的硫酸。 這些下賤眼睛，他們哪懂得我的們的生活。~ 據說，我曾經是人類
#+END_QUOTE

#+BEGIN_QUOTE
對，真的讓我噁心的，是對你們這些外人來說，我們這些人似乎非常悲慘，讓你們會用非常柔和的表情看我們，用非常虔誠的語調對我們講話。 ~ 據說，我曾經是人類
#+END_QUOTE

#+BEGIN_QUOTE
這世界裡裡外外都充滿了回音，供我們在音樂盒裡跳舞。 ~ 馬欣，當代寂寞考
#+END_QUOTE

#+BEGIN_QUOTE
不要拿鏡子給我，那裡沒有我認識的人。 ~ 馬欣，當代寂寞考
#+END_QUOTE

#+BEGIN_QUOTE
給他一張面具，他就會告訴妳實話。 ~ 奧斯卡。王爾德
#+END_QUOTE

#+BEGIN_QUOTE
為了榮耀那金碧輝煌的王座，他小得像什麼都沒有。 ~ 馬欣，當代寂寞考
#+END_QUOTE

* 兩性

#+BEGIN_QUOTE
到頭來,所有的女人都變得像自己的母親。那是女人的悲劇。可是 沒一個男人像自己的母親。那是男人的悲劇。 ~ 不可兒戲
#+END_QUOTE

* 親戚

#+BEGIN_QUOTE
老兄,我最愛聽人家罵我的親戚了。只有靠這樣,我才能忍受他 們。五親六戚都是一班討厭的人,完全不明白如何生得其道,也根本不領悟如何死得其時 ~ 不可兒戲
#+END_QUOTE

* 朋友

#+BEGIN_QUOTE
離開剛剛認識的人,總是令人難過的。老朋友不在身邊,倒可以心安理得地忍受。可是和剛剛介紹認得的人,就算是分離片刻,也教人幾乎受不了。  ~ 不可兒戲
#+END_QUOTE

* 欺騙

#+BEGIN_QUOTE
他們不是被我糊弄，而是被他們自己糊弄。一個人有了貪念，就不可能再有智商。 ~ 道士下山
#+END_QUOTE

* 惡念

#+BEGIN_QUOTE
惡念不是來自內心，而是不得志的生活。想消除惡念，先要改變生活。 ~ 道士下山
#+END_QUOTE

* 寂寞

#+BEGIN_QUOTE
山中巨大的寂寞令他精神衰弱，到了崩潰邊緣。為了內心的安靜，他回到了塵世。何安下捫心自問「你能不能從世上得到一個饅頭？」 ~ 道士下山
#+END_QUOTE

#+BEGIN_QUOTE
我必須大量的獨處，我的成就都是基於孤獨的努力。 ~ 法蘭茲，卡夫卡
#+END_QUOTE

#+BEGIN_QUOTE
印象中，我的影子總是看著我，後來我才知道那叫「寂寞」 ~ 馬欣，當代寂寞考
#+END_QUOTE

* 悲傷

#+BEGIN_QUOTE
我的故事是一首捧腹笑著唱出的悲傷之歌。如果你覺得故事太殘酷，那是因為我述說的方式太過誠實。 ~ 據說，我曾經是人類
#+END_QUOTE

* 罪惡感

#+BEGIN_QUOTE
罪惡感只是一種感覺，你可以選擇不要去感覺，要不然美國公司那些大老闆怎麼有辦法睡覺？ ~ 據說，我曾經是人類
#+END_QUOTE
* 社交網路
摘自 twitter

「她愛他恨他，他不知道。我都知道。可是他跟她是誰，我不知道。」
 像電線桿般立在一旁，不打擾別人生命中的瑣碎、任性與真誠。
