#+TITLE: 垃圾話
#+HTML_LINK_UP: ./index.html

* 會議室裡遺失的東西
K: 「有同學在會議室裡遺失重要的東西嗎？」

A: 「青春。」

source: bobchao's facebook.
* 笑即是殘酷 
Mikimoto: 根據幸福守恆定律，有生物笑的時候，一定有生物倒楣，所以笑的人都很殘酷。
* 生存、質疑與事故
Mikimoto: 所有的事情都會分成三個階段：「生存、質疑與世故」，例如以吃飯來說，一剛開始，你會告訴自己要吃飯，之後你會問為什麼要吃飯，最後你會問自己還有什麼東西可以吃
* 四句話總結人的一生
喜歡上一個人

喜歡上一個人

喜歡上一個人

喜歡上一個人

source: https://t.co/JQBvV4Hb2R
* JavaScript 帶給人類的啟示
javascript 告訴我們一件事，本身優不優秀不重要，重點是生對地方....
* 為什麼幸福的家庭都一個樣? 不幸的家庭都不一樣？
幸福的家庭都一個樣，不幸的家庭則家家有本難念的經。

為什麼呢？

讓工程師來告訴你：幸福的判斷式是 &&，不幸的判斷式是 ||；同時滿足所有條件才能變成幸福家庭，任一條件不滿足都會變成不幸家庭。
* 空虛與複雜
小孩的精神很豐富，所以他們的玩具很簡單。

大人的玩具很複雜，所以他們的精神很空虛。
* 矛盾何來
矛盾何來，皆因製杖販劍
* 一無所有
不要再說你一無所有了，你不是有病嗎？
* 跟工科大學生談生涯規劃
友人問曰: 「要跟大學生講職場、生涯規劃，大家覺得應該講些什麼」？

有鄉民答曰: 「工程師怎麼娶到好老婆的」

再有鄉民答曰: 「30歲前討到好老婆不能不知道的30件事」

友人妻奇道: 「所以取老婆比較重要？」

另有鄉民回道 :「娶對，就是人生。 娶錯，就是殘生。」
* 公司來了新人，姓蔡
男的叫蔡比巴, 女的叫菜菜子
* Duck Typing
什麼叫做 duck typing, 只要這個女生化妝起來像正妹，修圖後像正妹，整形後像正妹，那她就是個正妹。
* 熱情與初戀
Pingooo: 熱情就像初戀，一旦失去了，就很難追回來
* 阿宅都很忙
Jserv: 要說多少次，阿宅們都很忙碌的呀，不會因為居家就會很有空
* 要改的地方太多
Clkao: 要改的地方太多了，就改天
* 註定失敗
「從什麼時候開始決定你的人生注定失敗？」

『呃，當精子的時候？』
* 那就改天
改天就是永遠沒有那一天
* 大學專題該做什麼
Cindy: 專題就做 Lambda 仿生獸吧!

大二生: 這東西能做什麼用。

Cindy: 學生專題就是要做沒用但有梗的東西，要做有用能賺錢的東西，你之後的機會很多。
* 耐看
攝影師: 妳長得很耐看，但我沒有耐性
* 品味
何謂品味？何謂有追求？

就是讓一小部分有錢的人看出來你很有錢
* 王子救救我
公主：王子快救救我...

王子：現在救妳，故事就結束了....

眾人：......
* 如何猜星座
依據民法第124條，如果你不告訴我你的星座，我就猜你巨蟹座!
* 最貴重的生日禮物
A: 你收過最貴重的生日禮物是什麼？

B: 我媽給我的一條命。
* 友誼
友誼就是我智障多年，你卻不離不棄。

* 暖男變渣男
女: 為什麼暖男會變渣男?
友: 妳沒燒過煤嗎?

* 左眼跳財，右眼跳災
“人们常说左眼跳财，右眼跳灾。那我两个眼皮一起跳是什么意思？” “说明你的人身意外险快起作用了”我：。。。朋友，你这是欠揍啊！
* 正妹多久洗一次澡 
Q：正妹多久洗一次澡？A：宅男敲幾次就幾次。
* 為什麼宅男都不潮?
為什麼宅男都不潮? 因為宅男通常都有防潮箱
* 網站效能問題
創業的網站沒辦法遇到效能問題, 其實也是滿遺憾的 (恨意滿點)
* 無法原諒
當一個人對你做了無法原諒的事情時不要驚慌，因為原諒他是上帝的工作，我們的工作是送他去見上帝。
* 如何辨別跟你聊天的男生是電腦宅
如何辨別跟你聊天的男生是個電腦宅? A: 線上跟人聊天時, 萬一打錯字, 下一句會用"s/錯字/正確的字/"的人....
* 你是風兒我是沙
你是風兒我是沙，可是我這沙有點重，你可以當我的龍捲風嗎？
* ABCDEFGHIJK
女孩問：「ABCDEFG是什麼意思？」 男孩回答：「A Boy Can Do Everything For Girl」 
女孩又問：「那後面的HIJK呢？」 . . . . . . . . . 男孩：「He Is Just Kidding.」
* 不在 Facebook 寫出年齡的女生
我教你一件重要的事，不在 Facebook 寫出年齡的女性，基本上都超過26歲了。 ─《大人的心理學》
* 情人節與清明節的共通之處
情人節和清明節那是一樣一樣滴~都是送花送吃的
* 知識改變命運
一人去算命，算命先生摸骨相面掐算八字后，说，你二十岁恋爱，二十五岁结婚，三十岁生子，一生富贵平安家庭幸福晚年无忧。此人先惊后怒，道：我今年三十五岁，博士，光棍，木有恋爱。先生闻言，略微沉思后说：“年轻人，知识改变命运啊！”。。。
* 彩虹有幾種顏色?
彩虹有幾種顏色？ 同事：65536色
* 最平易近人的妖精
酒精大概是所有成精的妖精裡最平易近人的吧
* 人生只有四大問題
上不了班跟下不了班
睡不了覺跟睡太多覺
